# Generated by Django 5.2.7 on 2025-11-07 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalement',
            old_name='media',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='signalement',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='EN_COURS', max_length=10, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomMedia', models.CharField(max_length=255, verbose_name='Nom du média')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='core.signalement', verbose_name='Signalement')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'ordering': ['created_at'],
            },
        ),
    ]
