# Generated by Django 4.2.26 on 2025-11-20 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='IASignalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(max_length=100)),
                ('statut', models.CharField(max_length=20)),
                ('precision', models.FloatField(default=0.0)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.signalement')),
            ],
        ),
    ]
