# Generated by Django 4.2.26 on 2025-11-20 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_iasignalement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalement',
            name='photo',
        ),
        migrations.AddField(
            model_name='signalement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='signalements/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PhotoSignalements', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
    ]
