# Generated by Django 4.2.26 on 2025-11-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_signalement_photo_signalement_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalement',
            old_name='image',
            new_name='photo',
        ),
    ]
