# Generated by Django 4.2.26 on 2025-11-20 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_image_signalement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signalements', to='core.category', verbose_name='Categorie'),
        ),
    ]
