# Generated by Django 4.2.26 on 2025-11-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_signalement_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='signalements/', verbose_name='photo'),
        ),
    ]
