# Generated by Django 4.2.26 on 2025-11-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_signalement_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalement',
            name='photo',
        ),
        migrations.AddField(
            model_name='signalement',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='signalements/', verbose_name='Photo'),
        ),
    ]
