# Generated by Django 5.2.7 on 2025-11-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_signalement_photo_signalement_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalement',
            name='Photo',
        ),
        migrations.AddField(
            model_name='signalement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo'),
        ),
    ]
