# Generated by Django 4.2.26 on 2025-11-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_signalement_photo_signalement_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iasignalement',
            options={'ordering': ['-synced_at'], 'verbose_name': 'IASignalement', 'verbose_name_plural': 'IASignalements'},
        ),
    ]
